services:

  frontend:
    platform: linux/amd64
    build:
      context: ./RestaurankFrontend
    ports:
      - "5173:5173"
    working_dir: /app
    command: vite --host


  backend:
    build:
      context: ./RestaurankBackend
    ports:
      - "8000:8000"
    volumes:
      - ./RestaurankBackend:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
