version: '3.8'

services:
  frontend:
    build:
      context: ./RestaurankFrontend
    ports:
      - "5173:5173"
    volumes:
      - ./RestaurankFrontend:/app
      - /app/node_modules
    restart: unless-stopped

  backend:
    build:
      context: ./RestaurankBackend
    ports:
      - "8000:8000"
    volumes:
      - ./RestaurankBackend:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
